config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: %i[index show create new] do
    resources :reviews, ony: %i[create new]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true, inclusion: %w[chinese italian japanese french belgian]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.category = @restaurant.category.downcase
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def index
    @review = Review.find(params[:restaurant_id])
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurant</h1>

<% @restaurants.each do |restaurant| %>
  <div class="card">
    <h2 class="card-title"><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    <h4 class="card-text"><%= restaurant.address %></h4>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w[Chinese Italian Japanese French Belgian] %>
  <%= f.submit %>
<% end %>

app/views/restaurants/show.html.erb
<div class="card">
  <h1 class="card-title"><%= @restaurant.name %></h2>
  <h3 class="card-text"><%= @restaurant.address %></h4>
  <h4 class="card-text"><%= @restaurant.phone_number %></h5>
  <h4 class="card-text"><%= @restaurant.category.capitalize %></h5>
  <%= link_to 'Submit a Review', new_restaurant_review_path(@restaurant), class: "btn btn-primary" %>
  <%= link_to 'Back to Restaurants', restaurants_path, class: "btn btn-primary" %>
</div>

<div class="reviews">
  <% @reviews.each do |review| %>
    <div class="card review">
      <p class="card-title"><%= review.rating %></p>
      <p class="card-text"><%= review.content %></p>
    </div>
  <% end %>
</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>